name: rubicon-ml
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip

  - jupyterlab
  - rubicon-ml
  - python-kaleido
  - shap
  - numba=0.55.0

  # for scikit-learn examples
  - scikit-learn
