name: rubicon-ml-docs
channels:
  - conda-forge
dependencies:
  - python=3.9

  # for building the docs
  - black
  - furo
  - ipython
  - nbsphinx
  - numpydoc
  - sphinx
  - sphinx-copybutton
  - kaleido

  # only install necessary rubicon-ml dependencies
  - dash>=2.0.0
  - dash-bootstrap-components>=1.0.0
  - dask>=2.12.0
  - pandas>=1.0
  - fsspec>=2021.4.0
  - intake>=0.5.2
  - prefect>=0.12.0
  - scikit-learn
