name: rubicon-ml-docs
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip

  # for building the docs
  - black
  - furo
  - ipython
  - nbsphinx
  - numpydoc
  - sphinx
  - sphinx-copybutton


  # install rubicon-ml dependencies
  # so local pip install doesn't
  - dash<=2.17.1,>=2.11.0
  - dash-bootstrap-components<=1.6.0,>=1.0.0
  - fsspec<=2024.6.1,>=2021.4.0
  - intake<=2.0.5,>=0.5.2
  - jsonpath-ng<=1.6.1,>=1.5.3
  - numpy<=2.0.0,>=1.22.0
  - pandas<=2.2.2,>=1.0.0
  - prefect<=2.19.8,>=2.16.5
  - pyarrow<=16.1.0,>=14.0.1
  - PyYAML<=6.0.1,>=5.4.0
  - scikit-learn<=1.5.0,>=0.22.0
