name: rubicon-docs
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pip

  # for building the docs
  - furo
  - ipython
  - nbsphinx
  - numpydoc
  - sphinx
  - sphinx-copybutton

  # so pip doesn't actually install
  # the rubicon dependencies
  - click>=7.1
  - dash>=1.14.0
  - dash-bootstrap-components>=0.10.6
  - dask>=2.12.0
  - jupyter-dash
  - pandas>=1.0
  - fsspec
  - intake>=0.5.2
  - prefect>=0.12.0
  - pyarrow>=0.18.0
  - pyyaml>=5.4.0
  - s3fs>=0.4

  - pip:
    - ../
